### ISSUE TITLE
Criar cenário: personagem com colisão. - 5 pontos

### ISSUE THREAD

**Issue by alciomarhollanda** [UNASP-TI/vida10#11]
Criar cenário: personagem com colisão. - 5 pontos

**Comment by 1celo12** [comment]
https://github.com/UNASP-TI/vida10/assets/10713492/5fc9b21f-a5b0-4fc4-b497-988833bdb34f

**Comment by 1celo12** [comment]
> Recording.2023-10-14.082516.mp4

usando Axis-Aligned Bounding Box para colisao
