### ISSUE TITLE
Criar objeto casa - 5 Pontos

### ISSUE THREAD

**Issue by alciomarhollanda** [UNASP-TI/vida10#12]

**Comment by Isaiaz1** [comment]
<img width="394" alt="Screenshot_1casaetc" src="https://github.com/UNASP-TI/vida10/assets/59181631/ef542fcc-e237-474c-b10e-2e5658b5cc4a">
<img width="800" alt="Screenshot2233" src="https://github.com/UNASP-TI/vida10/assets/59181631/0dbd4282-9685-4544-bed8-dc4d0b511ea0">
<img width="949" alt="Screenshot11" src="https://github.com/UNASP-TI/vida10/assets/59181631/14260b35-f595-41bb-8a29-e898e3f532e6">

Script em C# do objeto casa

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NewBehaviourScript  : MonoBehaviour
 // NewBehaviourScript : MonoBehaviour
{
     //variaveis do objeto que aparecem no projeto
    // Start is called before the first frame update
 [SerializeField]private int NumeroDeQuartos = 2;
 [SerializeField]private int NumeroDePortas = 3;
    
    private MeshRenderer MeshRenderer;
  private float horizontal;
  private float vertical;
  [SerializeField]private int velocidade;

    void Start()
    {
         NumeroDePortas = 3;
        NumeroDeQuartos = 2;
        MeshRenderer = GetComponent<MeshRenderer>();
    }

    // Update is called once per frame
    void Update()
    {
        Sumir();
        Mover();
    }
 //Mover o objeto
void Mover(){
 horizontal = Input.GetAxis("Horizontal");
vertical = Input.GetAxis("Vertical");

transform.Translate(new Vector3(horizontal,vertical,0)*Time.deltaTime*velocidade);   
}
 //animaçao de desativar o objeto
void Sumir(){
    if (Input.GetKeyDown(KeyCode.C)){
    gameObject.SetActive(!gameObject.activeSelf); 
}

}
}`

**Comment by Isaiaz1** [comment]
![New Piskelcasa1 (22)](https://github.com/UNASP-TI/vida10/assets/59181631/fcad09cf-eff3-43e3-a9e4-4d765721a754)
![New Piskelcasa11](https://github.com/UNASP-TI/vida10/assets/59181631/90ac0cd6-e7ae-4c49-83b6-76b874cf2670)
<img width="942" alt="Screenshot_1newcasa3010" src="https://github.com/UNASP-TI/vida10/assets/59181631/747e5a1b-e468-444f-b07e-8498656b234e">



` using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NewBehaviourScript  : MonoBehaviour
 // NewBehaviourScript : MonoBehaviour
{
     //variaveis do objeto que aparecem no projeto
    // Start is called before the first frame update
 [SerializeField]private int NumeroDeQuartos = 2;
 [SerializeField]private int NumeroDePortas = 3;
    
    private MeshRenderer MeshRenderer;
  private float horizontal;
  private float vertical;
  [SerializeField]private int velocidade;

    void Start()
    {
         NumeroDePortas = 3;
        NumeroDeQuartos = 2;
        MeshRenderer = GetComponent<MeshRenderer>();
    }

    // Update is called once per frame
    void Update()
    {
        Sumir();
        Mover();
    }
 //Mover o objeto
void Mover(){
 horizontal = Input.GetAxis("Horizontal");
vertical = Input.GetAxis("Vertical");

transform.Translate(new Vector3(horizontal,vertical,0)*Time.deltaTime*velocidade);   
}
 //animaçao de desativar o objeto
void Sumir(){
    if (Input.GetKeyDown(KeyCode.C)){
    gameObject.SetActive(!gameObject.activeSelf); 
}

}
} `
