### ISSUE TITLE
Criar objeto árvore - 8 pontos

### ISSUE THREAD

**Issue by alciomarhollanda** [UNASP-TI/vida10#13]

**Comment by ghost** [comment]
![Layer 1_sprite_1](https://github.com/UNASP-TI/vida10/assets/70244317/0447fe68-6cfc-444a-9334-d20ec5505729)
![Layer 1_sprite_2](https://github.com/UNASP-TI/vida10/assets/70244317/26c46348-c727-4a53-a862-dacce518f0f2)
![Layer 1_sprite_3](https://github.com/UNASP-TI/vida10/assets/70244317/0c968c11-ed16-40fe-8b2d-1ba0b492cde3)
![Layer 1_sprite_4](https://github.com/UNASP-TI/vida10/assets/70244317/a938b220-2677-441e-b7ac-74f1ac931266)
![Layer 1_sprite_5](https://github.com/UNASP-TI/vida10/assets/70244317/b505e078-423b-47a0-8413-2948a1d56f2e)
![Layer 1_sprite_6](https://github.com/UNASP-TI/vida10/assets/70244317/c612cc8d-15a5-47c8-b1d1-d886c9ec9c30)
![New Piskel](https://github.com/UNASP-TI/vida10/assets/70244317/25825ef4-31e5-4480-a76c-2260842f7ae3)

**Comment by ghost** [comment]
Segue imagens dos andamentos da criação
