### ISSUE TITLE
Game - Criar tilemap do chão no angulo diagonal em pixelart (apenas a grama e grama e terra)

### ISSUE THREAD

**Issue by rubenhanderson** [UNASP-TI/vida10#18]

**Comment by cesar8389** [comment]
![grama topo](https://github.com/UNASP-TI/vida10/assets/19841745/c688276c-4a45-4d3c-a73b-27ef4345eadd)
![grama-baixo](https://github.com/UNASP-TI/vida10/assets/19841745/0814f942-fcd5-452a-acbc-9b5f5aa6ac86)
![grama-centro](https://github.com/UNASP-TI/vida10/assets/19841745/83012ea3-b1b2-4d53-a895-1fcabe65a8dd)
![grama-direita](https://github.com/UNASP-TI/vida10/assets/19841745/2ae0b3db-f6ff-4414-8437-be266f9fc037)
![grama-esquerda](https://github.com/UNASP-TI/vida10/assets/19841745/bb250550-2e0a-44cd-80b5-0d6e0fc33af5)
![grama-inferiordireito](https://github.com/UNASP-TI/vida10/assets/19841745/a95e8bd5-5c1c-43ab-b278-d73a5e5c0745)
![grama-inferioresquerdo](https://github.com/UNASP-TI/vida10/assets/19841745/d1f4d820-1c70-49b9-a814-fd28f8f4b698)
![grama-superiordireito](https://github.com/UNASP-TI/vida10/assets/19841745/10dcab0e-1203-4e99-a2e9-8b880dcc5b5e)
![grama-superioresquerdo](https://github.com/UNASP-TI/vida10/assets/19841745/392d3b94-0165-46c6-8b7a-9965013dc411)
![terra](https://github.com/UNASP-TI/vida10/assets/19841745/896f9187-ac3d-452a-b9a8-934762b49f2f)
