### ISSUE TITLE
Estudo de música em jogos. Criar documento.   - 8 pontos

### ISSUE THREAD

**Issue by alciomarhollanda** [UNASP-TI/vida10#2]

**Comment by Isaiaz1** [comment]
[Estudo de música em jogos. Criar documento1.1.docx](https://github.com/UNASP-TI/vida10/files/12787013/Estudo.de.musica.em.jogos.Criar.documento1.1.docx)

**Comment by ghost** [comment]
[Músicas nos jogos.pdf](https://github.com/UNASP-TI/vida10/files/12848448/Musicas.nos.jogos.pdf)
[Músicas nos jogos.docx](https://github.com/UNASP-TI/vida10/files/12848449/Musicas.nos.jogos.docx)
