### ISSUE TITLE
VR - Aprender e trazer sugestões de ferramentas para VR

### ISSUE THREAD

**Issue by rubenhanderson** [UNASP-TI/vida10#21]
Critério de Aceite

- [ ] Sistema de programação é gratuito?
- [ ] Consegue inserir Vídeo Youtube?
- [ ] Consegue inserir PDF?

**Comment by 1celo12** [comment]
[VR Development platforms Sprint 4.docx](https://github.com/UNASP-TI/vida10/files/13339301/VR.Development.platforms.Sprint.4.docx)

**Comment by Vida10MCR** [comment]
Foi verificado  utilizar o Unit e também fazer teste na prática utilizando o PANO2VR.
