### ISSUE TITLE
VR - Aprender e trazer informações de como utilizar o Pano2VR  (Objetivo: Ter um ambiente que seja próprio)

### ISSUE THREAD

**Issue by rubenhanderson** [UNASP-TI/vida10#22]
https://ggnome.com/pano2vr/

Critério de Aceite 

- [ ] Navegar por um ambiente
- [ ] É possível criar em um link e abrir um vídeo do Youtube?
- [ ] É possível inserir um arquivo PDF?

@Giovanni-Andretta 
@rubenhanderson 
@BrunoReis70

**Comment by alciomarhollanda** [comment]
Atividade desenvolvida pelo @Giovanni-Andretta  e @BrunoReis70 
Opa pessoal, boa tarde, sobre o tema que discutimos semana passada de: pano2vr vs unity.

Eu e o Bruno pesquisamos sobre, comparando as ferramentas com pros e contras tivemos achamos esse site que faz justamente isso:

https://www.softwareadvice.com/virtual-reality/pano2vr-profile/vs/unity/

Onde, concordamos com base nas infos que, a melhor ferramenta para implantar a mecânica do VR seria o unity, justamente por conta da compatibilidade do vida10 ter sido feito inteiramente no unity, e a capacidade flexível da ferramenta de aplicar suas necessidades e também pela quantidade de vídeos auto explicativos de como fazer certa mecânica.

Nessa linha de raciocínio, pesquisamos como seria a implantação do VR no unity, e acreditamos que com o XR plug-in isso é possível.

https://docs.unity3d.com/Manual/XR.html

Também pesquisamos a possibilidade de criar o jogo sem que a pessoa precise dos óculos VR e os controles, e também a interação com os links que o Marcelo comentou:

https://youtu.be/WELSs-lPJYA?si=-Dsg_VmJClXzTH04

https://youtu.be/qqOqLNqAdDo?si=Iik2NRrr-1XflZrF
