### ISSUE TITLE
Rodar vídeo dentro do ambiente virtual

### ISSUE THREAD

**Issue by rubenhanderson** [UNASP-TI/vida10#27]
De preferência rodar o vídeo de dentro da aplicação. Uma outra opção seria fazer o embed do vídeo do youtube.

**Comment by GenesisCarvalho** [comment]
Vou fazer essa atividade.

**Comment by rubenhanderson** [comment]
achei um tutorial. bem simples. é só adicionar o vídeo como asset 

https://www.youtube.com/watch?v=-XzVq7qIuys
