### ISSUE TITLE
Gamificação em jogos. Criar documento. - 8 pontos

### ISSUE THREAD

**Issue by alciomarhollanda** [UNASP-TI/vida10#3]

**Comment by 1celo12** [comment]
achei 2 pesquisas informativas. uma e um resumo da literatura sobre gamificao de 2012. ourto e uma meta-analasise dos beneficios de gamificao. Depois fiz um resumo de ideas funadmentais a o assunto e recomendacoes dos procimos passos.
[Gamificacao Pesquisas 00.pdf](https://github.com/UNASP-TI/vida10/files/12823019/Gamificacao.Pesquisas.00.pdf)

**Comment by 1celo12** [comment]
[Gamificacao Pesquisas 00.pdf](https://github.com/UNASP-TI/vida10/files/12849939/Gamificacao.Pesquisas.00.pdf)
 
Em PT/IN
