### ISSUE TITLE
Estudar piskelapp de como integrar com unity. Criar documento. - 8 pontos

### ISSUE THREAD

**Issue by alciomarhollanda** [UNASP-TI/vida10#4]

**Comment by SamuelPaimAraujoCezar** [comment]
Integrar o Piskel (um editor online de pixel art) com o Unity pode ser feito de maneira relativamente simples. Aqui estão os passos básicos:

1. Crie uma Sprite no Piskel:
•	Vá para o [PiskelApp](https://www.piskelapp.com/).
•	Crie ou edite sua sprite pixel por pixel.
2. Exporte a Sprite:
•	Depois de criar ou editar a sprite, exporte-a em um formato suportado pelo Unity, como PNG.
3. Importe a Sprite no Unity:
•	Abra o Unity e vá para o projeto onde deseja importar a sprite.
•	Coloque o arquivo da sprite exportada na pasta Assets do seu projeto.
4. Configure a Sprite:
•	Selecione a sprite na pasta Assets.
•	No Inspector, certifique-se de que o tipo seja "Sprite (2D and UI)".
•	Ajuste outros parâmetros conforme necessários.
5. Use a Sprite em seu Jogo:
•	Agora, você pode usar a sprite em seus GameObjects no Unity. Arraste e solte-a em um objeto ou crie um SpriteRenderer e atribua a sprite a ele.

Lembre-se de ajustar a escala e outras configurações para se adequar ao seu jogo. Certifique-se de que o PiskelApp exportou a sprite em uma resolução que funciona bem para o seu projeto no Unity.

**Comment by pedroha-dev** [comment]
Sobre algumas ferramentas para fazer Sprite e como passar para o Unity.

O [Piskel](https://www.piskelapp.com) é uma ferramenta online, ou seja, você pode utilizar no navegador sendo totalmente gratuito, ou caso você queira [baixar](https://www.piskelapp.com/download), mas baixando você não terá acesso a nenhum Sprite que foi feito no navegador.  O Piskel tem uma interface bem simples e de fácil entendimento.
[Manual do Piskel](https://producaodejogos.com/piskel-guia-para-pixel-art-e-sprites-animados/) informando atalhos e como utilizar cada ferramenta e configurações.

Outra ferramenta muito utilizada em criação de Sprite é o [Aseprite](https://store.steampowered.com/app/431730/Aseprite/) possui mais ferramentas e recursos do que o Piskel, mas não é gratuito. 
[Manual do Aseprite](https://www.aseprite.org/docs/tutorial/) informando atalhos e como utilizar cada ferramenta e configurações.

No [manual](https://docs.unity3d.com/Manual/sprites-setup.html) do Unity informa que temos dois métodos para importar Sprites:

- No File Explorer do seu computador, coloque sua imagem diretamente na pasta Assets do seu projeto Unity . O Unity detecta isso e exibe na Project view.
- No Unity, vá para Assets > Import New Asset . Na janela do File Explorer  que é aberta, selecione a imagem escolhida. O Unity exibe a imagem escolhida na visualização do projeto .

Se você definir seu projeto como 2D , o Unity definirá automaticamente a imagem importada como um sprite. O Unity também criará sprites automaticamente com base no comportamento do Fatiamento Automático na janela do Editor de Sprite . Se você definir seu projeto para 3D, o Unity importará sua imagem como uma textura. Para alterar o tipo de textura do ativo :

- Selecione o ativo para acessar sua Import Inspector.
- Defina o tipo de textura como Sprite (2D e UI).
