### ISSUE TITLE
Estudo de versionamento de projeto unity para github. - 8 pontos

### ISSUE THREAD

**Issue by alciomarhollanda** [UNASP-TI/vida10#5]

**Comment by GustavoFerrera** [comment]
Versionamento de projetos Unity com o GitHub é uma prática essencial para colaboração eficiente e rastreamento de alterações ao longo do desenvolvimento do jogo.

Passos para configurar o projeto Unity com o Git e por fim hospeda-lo no GitHub:

**Passo 1: Configurar o Git:**

Abra o terminal ou prompt de comando para configurar o Git globalmente:


git config --global user.name "GustavoFerrera"
git config --global user.email "gustavo.ferrera.nasc@gmail.com"

**Passo 2: Criar um repositório no GitHub:**

Crie um repositório com o nome de sua preferência.

**Passo 3: Inicializar o Git no seu projeto Unity:**

Abra o projeto Unity.
Abra a janela do Terminal no Unity, que pode ser encontrada em "Window" > "General" > "Terminal".
Navegue até a pasta raiz do projeto Unity usando o terminal.
Execute os seguintes comandos para iniciar o repositório Git e adicionar os arquivos ao controle de versão:

git init
git add .
git commit -m "Primeiro commit"

**Passo 4: Conectar o repositório local ao GitHub:**

Volte ao GitHub e copie o URL do seu repositório recém-criado.
No terminal do Unity, adicione o URL do repositório remoto usando o seguinte comando (substitua <URL do Repositório> pelo URL do seu repositório):

git remote add origin <URL do Repositório>

**Passo 5: Enviar o projeto para o GitHub:**

Para enviar o projeto para o GitHub, use o seguinte comando:

git push -u origin master

A partir deste ponto, você pode continuar trabalhando no seu projeto Unity normalmente. Sempre que você fizer alterações significativas, você pode usar os seguintes comandos Git para atualizar seu repositório no GitHub:

git add . : Adicionar as mudanças ao stage.
git commit -m "Mensagem de commit": Commit das mudanças.
git push origin master: Enviar as mudanças para o GitHub.

Além disso, você pode criar branches para trabalhar em recursos separados e fundi-los quando estiverem prontos. O controle de versão no GitHub permitirá que você rastreie todas as mudanças e colabore com outros desenvolvedores de forma eficiente.
