### ISSUE TITLE
Estudo de publicação de jogos para as plataforma - 8 pontos

### ISSUE THREAD

**Issue by alciomarhollanda** [UNASP-TI/vida10#6]

**Comment by cesar8389** [comment]
<h2>Apple Store</h2>
    <p>Para a publicação de aplicativos na loja da Apple é preciso uma inscrição no Apple Developer Program utilizando
        um ID Apple com autenticação de dois fatores ativa. Além de pagar o valor de US$99 por ano, é necessário
        informar alguns dados:
    <ul>
        <li>Status de pessoa jurídica</li>
        É exigido que seja uma pessoa juridica para poder assinar um contrato com a Apple e não pe aceito um nome
        fantasia. O nome da pessoa juridica aparece como o nome do vendedor que está distribuindo os apps.
        <li>Número D‑U‑N‑S</li>
        O número D-U-N-S serve para verificar o status de pessoa juridica e é emitido por Dun & Bradstreet. Esse número
        de 9 digitos é equivalente ao CNPJ brasileiro.
        <li>Autoridade legal vinculante</li>
        A pessoa que fizer a inscrição da empresa deve ter algum grau de senerioridade dentro da empresa, como por
        exemplo o proprietario/fundador, líder de projetos sênior ou representante legal.
        <li>Site</li>
        É necessário ter um site público com um nome de dominio associado a ele.
    </ul>
    </p>
    <h2>Play Store</h2>
    <p>No caso da Play Store as exigencias não mudam, inclusive o número D-U-N-S. A taxa também muda, aqui o valor é de
        US$25 que é pago apenas quando a conta é criada e não necessita de um valor anual para renovação.</p>

**Comment by cesar8389** [comment]
<h2>Unity</h2>
    <p>A plataforma Unity não possui custo de licenciamento para estudantes, mas no caso de empresas o licenciamento
        parte de R$11.791,00 anuais mas traz mais vantagens, como personalização da tela de carregamento e prioridade no
        atendimento do suporte técnico.
        Também existe o plano Personal, que é o mais utilizado por desenvolvedores independentes e que até o momento
        também é grátis. É previsto mudanças nesta categoria a partir de 1 de janeiro de 2024, conforme mostra a tabela
        abaixo retirada na integra no site oficial da Unity. Vale lembrar que mudanças ainda podem ocorrer, visto que a
        comunidade não aceitou bem essas novas taxas e podem acabar abandonando a plataforma.
    </p>
    <table class="table-desktop" style="width:100%;border:1px;border-style:solid;border-color:#000000">
        <thead>
            <tr style="background-color:#000000;color:#ffffff">
                <td colspan="4" style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>Tabela
                        da Taxa de Tempo de Execução do Unity</strong><br>
                    Verifique se a taxa de tempo de execução do Unity se aplica ao seu jogo e estime as possíveis taxas
                    aplicáveis. A taxa é valida para novas instalações a partir de 1 de janeiro de 2024, faturada
                    mensalmente.</td>
            </tr>
            <tr style="background-color:#2196f3;color:#ffffff">
                <td colspan="4" style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>Passo 1:
                        Verifique Sua Elegibilidade</strong><br>
                    O seu jogo deve atender aos limites de receita E instalação para que a taxa seja aplicada.</td>
            </tr>
            <tr style="background-color:#eeeeee;color:#000000">
                <th style="padding:10px;border:1px;border-style:solid;border-color:#000000" width="18%">&nbsp;</th>
                <th style="padding:10px;border:1px;border-style:solid;border-color:#000000" width="27%"><strong>Unity
                        Personal e Unity Plus</strong></th>
                <th style="padding:10px;border:1px;border-style:solid;border-color:#000000" width="28%"><strong>Unity
                        Pro</strong></th>
                <th style="padding:10px;border:1px;border-style:solid;border-color:#000000" width="27%"><strong>Unity
                        Enterprise</strong></th>
            </tr>
            <tr>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>Limite de receita
                    </strong>(últimos 12 meses)</td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 200.000,00</td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 1.000.000,00</td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 1.000.000,00</td>
            </tr>
            <tr>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>Limite de
                        instalações </strong>(ao longo da vida útil do jogo)</td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">200.000</td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">1.000.000</td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">1.000.000</td>
            </tr>
            <tr style="background-color:#2196f3;color:#ffffff">
                <td colspan="4" style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>Passo 2:
                        Calcule a Taxa</strong><br>
                    Se o seu jogo atinge ambos os critérios (limites de receita e instalação), as taxas escalonadas
                    serão aplicadas e cobradas uma vez por cada nova instalação.</td>
            </tr>
            <tr style="background-color:#eeeeee;color:#000000">
                <th style="padding:10px;border:1px;border-style:solid;border-color:#000000" width="18%">&nbsp;</th>
                <th style="padding:10px;border:1px;border-style:solid;border-color:#000000" width="27%"><strong>Unity
                        Personal e Unity Plus</strong></th>
                <th style="padding:10px;border:1px;border-style:solid;border-color:#000000" width="28%"><strong>Unity
                        Pro</strong></th>
                <th style="padding:10px;border:1px;border-style:solid;border-color:#000000" width="27%"><strong>Unity
                        Enterprise</strong></th>
            </tr>
            <tr style="background-color:#595959;color:#ffffff">
                <td style="padding:10px;border:1px;border-style:solid;border-color:#ffffff"><strong>Novas instalações
                        por mês</strong></td>
                <td colspan="3" style="padding:10px;border:1px;border-style:solid;border-color:#ffffff"><strong>Taxa
                        padrão (se os critérios forem atingidos)</strong></td>
            </tr>
            <tr>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>1 a 100.000</strong>
                </td>
                <td rowspan="4" style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,20 por
                    nova instalação</td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,15 por nova instalação
                </td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,125 por nova
                    instalação</td>
            </tr>
            <tr>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>100.001 a
                        500.000</strong></td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,075 por nova
                    instalação</td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,06 por nova instalação
                </td>
            </tr>
            <tr>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>500.001 a
                        1.000.000</strong></td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,03 por nova instalação
                </td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,02 por nova instalação
                </td>
            </tr>
            <tr>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>Mais de
                        1.000.001</strong></td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,02 por nova instalação
                </td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,01 por nova instalação
                </td>
            </tr>
            <tr style="background-color:#000000;color:#ffffff"></tr>
            <tr style="background-color:#595959;color:#ffffff">
                <td style="padding:10px;border:1px;border-style:solid;border-color:#ffffff"><strong>Novas instalações
                        por mês</strong></td>
                <td colspan="3" style="padding:10px;border:1px;border-style:solid;border-color:#ffffff"><strong>Taxa
                        para mercados emergentes (se os critérios forem atingidos)</strong></td>
            </tr>
            <tr>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000"><strong>Mais de 1</strong>
                </td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,02 por nova instalação
                </td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,01 por nova instalação
                </td>
                <td style="padding:10px;border:1px;border-style:solid;border-color:#000000">US$ 0,005 por nova
                    instalação</td>
            </tr>
        </thead>
    </table>
    <i>Retirado de https://blog.unity.com/pt/news/plan-pricing-and-packaging-updates em 08 de outubro de 2023</i>
