### ISSUE TITLE
Configurar o unity no computador (Todos Devs) - v2022.3 - 5 pontos

### ISSUE THREAD

**Issue by alciomarhollanda** [UNASP-TI/vida10#8]
Todos os integrantes precisam instalar o unity : https://unity.com/pt/download

**Critério de aceite**
- [x]  Enviou uma imagem do unity instalado no seu computador?
- [ ]

**Comment by Isaiaz1** [comment]
![imagem_2023-10-10_212436785](https://github.com/UNASP-TI/vida10/assets/59181631/bd98aa91-1202-4031-ac76-7d3b74902932)

**Comment by 1celo12** [comment]
<img width="1920" alt="unity install sprint" src="https://github.com/UNASP-TI/vida10/assets/10713492/26912c9e-8ff4-4fbe-976c-95e7494d620b">

**Comment by SamuelPaimAraujoCezar** [comment]
![Image](https://github.com/UNASP-TI/vida10/assets/71200435/3e973dfb-5ae8-4c8c-b253-4b5608bf0d77)

**Comment by ghost** [comment]
![image](https://github.com/UNASP-TI/vida10/assets/70244317/e5796ec1-400c-4c3e-9402-1f6fb1a38a75)

**Comment by cesar8389** [comment]
![image](https://github.com/UNASP-TI/vida10/assets/19841745/72af96be-9c01-49a6-a085-c7fe15b71d4c)

**Comment by pedroha-dev** [comment]
![image](https://github.com/UNASP-TI/vida10/assets/146035846/2d6d6c96-5794-46ea-a28d-f4eb7bc7e63c)

**Comment by GustavoFerrera** [comment]
![unity](https://github.com/UNASP-TI/vida10/assets/84362116/7395ce60-c8cb-4745-8997-a755932ea099)

**Comment by viniciusvexter** [comment]
![Screenshot 2023-11-12 at 17 17 07](https://github.com/UNASP-TI/vida10/assets/46562442/1ed349db-0dbf-4799-9789-d0b38dbaef41)
